name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-unit-tests:

    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM Dependancies
      run: npm install
    - name: Run the Unit tests
      run: npm run test:unit
    - name: Display my Softuni Username
      run: echo "napetkov"
  
  build-run-ui-tests:
    needs: build-unit-tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository 
      uses: actions/checkout@v4
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install NPM dependancies
      run: npm install
    - name: Install NPX Playwright browsers
      run: npx playwright install
    - name: Start Application
      run: npm start &
    - name: Run the UI tests
      run: npm run test:ui

  deploy-production:
    needs: build-run-ui-tests
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: JorgeLNJunior/render-deploy@v1.4.4
      with:
        service_id: ${{ secrets.MY_RENDER_SERVICE_ID }}
        api_key: ${{ secrets.MY_RENDER_API_KEY }}
        wait_deploy: true